### ISSUE TITLE
can not convert mobilenetv2

### ISSUE THREAD

**Issue by kkkch** [nyoki-mtl/pytorch-segmentation#14]
The command which convert the pretrained model(MobilenetV2) to pytorch is mistake.
Maybe correct command is
`$ python -m converter.convert_mobilenetv2 ../tf_model/deeplabv3_mnv2_cityscapes_train/model.ckpt 19 ../model/cityscapes_mobilnetv2/model.pth`

And, this error is occurred
> FileNotFoundError: [Errno 2] No such file or directory: '../model/mobilenetv2_encoder/model.pth'

I solve it, change `src/models/net.py` line 92 `pretrained=False`.

Is it OK?

**Comment by FlYWMe** [comment]
The converted mobilenetv2 model.pth is wrong. There are many unexpected keys in state_dict.

**Comment by narendoraiswamy** [comment]
@FlYWMe . I would suggest you to go through the code and make the necessary changes in it as the default encoders and decoders have to be changed for using the mobilenetv2 checkpoint.

**Comment by manueldiaz96** [comment]
Has anyone solved this? 
Care to share or do a pull request?
Thanks!

**Comment by nyoki-mtl** [comment]
Sorry for late reply.
I fixed it.
