### ISSUE TITLE
Error: No module named 'pretrainedmodels' when running convert.py

### ISSUE THREAD

**Issue by wyfeng1020** [nyoki-mtl/pytorch-segmentation#3]
Hi, thanks for sharing your wonderful work! But when I try to run convert.py, there occurs a no-module error of 'pretrainedmodels' in './src/models/encoder.py'.  Did you miss the file or I miss some depending packages?

**Comment by nyoki-mtl** [comment]
@wyfeng1020 
You need [pretrainedmodels](https://github.com/Cadene/pretrained-models.pytorch).
You can install from pip.
```
pip install pretrainedmodels
```

**Comment by wyfeng1020** [comment]
That solved the problem, Thanks!
